flags: {}
packages:
- './easyspec'
- './easyspec-evaluate'
- location:
      git: git@github.com:NorfairKing/quickspec.git
      commit: d4ee1a3737a210e22cd9aabb0a3c0710276d31f3
  extra-dep: true
extra-deps:
- optparse-applicative-0.13.2.0
- validity-containers-0.1.0.2
- quickspec-0.9.6
- validity-0.3.2.0
- validity-path-0.1.0.0
- genvalidity-0.3.1.0
- genvalidity-hspec-0.3.1.0
- genvalidity-path-0.1.0.0
- jukebox-0.2.14
- twee-0.1
- minisat-0.1.2
resolver: lts-8.6
